<?php

/**
* @file
* A block module that displays a form for edit taxonomy terme.
*/

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/
function taxo_status_help($path, $arg) {
  switch ($path) {
    case "admin/help#taxo_status":
      return '<p>' . t("Displays form for simple taxo term edit") . '</p>';
      break;
  }
} 

/**
* Implements hook_block_info().
*/
function taxo_status_block_info() {
  $blocks['taxo_status'] = array(
    'info' => t('Taxo edit'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

/**
* Access control
*
* For edit taxo by form, and by external file
*
*/

function taxo_status_permission(){
	return array(
		'administer taxo editor' => array(
			'title' => t('Administer the taxo editor'),
			'description' => t('Configure, vocabulary, term and form type')
		),
	  'edit term by file' => array(
			'title' => t('Edit taxo term by file'),
			'description' => t('Edit taxonomy term by .php file, useful for auto updates')
		)
	);

}


/**
* Implements hook_menu().
*/
function taxo_status_menu() {
  $items = array();
  
  $items['admin/config/content/taxo_status'] = array(
  	'title' => 'Taxo Term Editor',
  	'description' => 'Configuration for Taxo Term Editor module',
  	'page callback' => 'drupal_get_form',
  	'page arguments' => array('taxo_status_form'),
  	'access arguments' => array('access administration pages'),
  	'type' => MENU_NORMAL_ITEM,
  	'file' => 'taxo_status.admin.inc'
  	);
  return $items;
}

/**
* Custom content function.
*
* Look witch term edit
*
* @return
*   Taxonomy tid to edit in block
*/
function taxo_status_contents(){
	$taxo_terms = array();
	$tids = array("1", "6");
	foreach ($tids as $tid) {
		array_push($taxo_terms, taxonomy_term_load($tid));
	}
	return $taxo_terms;
}

/**
* Block view
*
* Contenu du block
*/

function taxo_status_block_view(){
	$vid = variable_get('taxo_status_vid');
  $display_terms = taxo_status_contents();
	if(user_access("edit terms in".$vid)){
		$block['content'] = '<p>Edit Form</p>';
		foreach($display_terms as $display_term){
				$value = field_get_items('taxonomy_term', $display_term, 'field_state');
				if ($value){
					$value = $value[0]['value'];
				}
				else{
					$value = t('Empty');
				}
			$block['content'] .= '<p>'.$display_term->name.' = '.$value.'</p>';
		}
	}
	else{
		$block['content'] = '<ul>';
		foreach($display_terms as $display_term){
				$value = field_get_items('taxonomy_term', $display_term, 'field_state');
				if ($value){
					$value = $value[0]['value'];
				}
				else{
					$value = t('Empty');
				}
			$block['content'] .= '<li>'.$display_term->name.' = '.$value.'</li>';
		}
		$block['content'] .='</ul>';
	}
	return $block;
}



